package gov.nih.nlm.ckn;

import java.util.List;
import lombok.*;

/**
  Material anatomical entity that is a single connected structure with inherent 3D shape generated by coordinated expression of the organism's own genome.
**/
@Data
@EqualsAndHashCode(callSuper=false)
public class AnatomicalStructure {

  private String exactSynonym;
  private String label;
  private String ontologyPurl;
  private String databaseCrossReference;

}